AdvertisementProject/AdvertisementApp/AdvertisementApp.Presentation/Controllers/ApplicationController.cs
using AdvertisementApp.Business.Interfaces;
using AdvertisementApp.Dtos;
using AdvertisementApp.Presentation.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace AdvertisementApp.Presentation.Controllers
{
    public class ApplicationController : Controller
    {

        private readonly IAdvertisementService _advertisementService;

        public ApplicationController(IAdvertisementService advertisementService)
        {
            _advertisementService = advertisementService;
        }
        public async  Task<IActionResult> List()
        {
            var response = await _advertisementService.GetAllAsync();

            return this.ResponseView(response);


        }


        public IActionResult Create()
        {
            return View(new AdvertisementCreateDto());
        }


        [HttpPost]
        public async Task<IActionResult> Create(AdvertisementCreateDto dto)
        {
            var response =await _advertisementService.CreateAsync(dto);
            return this.ResponseRedirectAction(response, "List");
        }


        public async Task<IActionResult> Update(int id)
        {
            var response = await _advertisementService.GetByIdAsync<AdvertisementUpdateDto>(id);

            return this.ResponseView(response);
        }

        [HttpPost]
        public async Task<IActionResult> Update(AdvertisementUpdateDto dto)
        {
            var response = await _advertisementService.UpdateAsync(dto);

            return this.ResponseRedirectAction(response, "List");
        }


        public async Task<IActionResult> Remove(int id)
        {
            var response = await _advertisementService.RemoveAsync(id);
            return this.ResponseRedirectAction(response, "List");
        }
    }
}

AdvertisementProject/AdvertisementApp/AdvertisementApp.Presentation/Views/Application/Create.cshtml
@model AdvertisementCreateDto
@{
 
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
        <form asp-action="Create" asp-controller="Application" method="post">
            <div class="mb-3"> 
                <label> İlanın Başlığı </label>
                <input  type="text" class="form-control" asp-for="@Model.Title"/>
            </div>
             <div class="mb-3"> 
                <label class="form-check-label"> Aktif </label>
            <input  type="checkbox" class="form-check-input" asp-for="@Model.status"/>
            </div>

            <div class="mb-3">
                <lable> İçerik</lable>
                <textarea asp-for="@Model.Description" class="form-control"> </textarea>

            </div>
            <div class="mb-3">

                <button class="btn btn-primary"> Kaydet</button>
            </div>
        </form>

</div>


@section script{

        <script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
         <script>window.jQuery || document.write('<script src="js/vendor/jquery-3.3.1.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.26.0/trumbowyg.min.js" integrity="sha512-ZfWLe+ZoWpbVvORQllwYHfi9jNHUMvXR4QhjL1I6IRPXkab2Rquag6R0Sc1SWUYTj20yPEVqmvCVkxLsDC3CRQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

        <script>
            $(document).ready(function()
            {
            $("#Description").trumbowyg();
            
            });
        </script>
}

@section css{

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.26.0/ui/trumbowyg.min.css" integrity="sha512-Zi7Hb6P4D2nWzFhzFeyk4hzWxBu/dttyPIw/ZqvtIkxpe/oCAYXs7+tjVhIDASEJiU3lwSkAZ9szA3ss3W0Vug==" crossorigin="anonymous" referrerpolicy="no-referrer" />
}

AdvertisementProject/AdvertisementApp/AdvertisementApp.Presentation/Views/Application/List.cshtml
@model List<AdvertisementListDto>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<div class="container">



    @{
        if (Model?.Count > 0)
        {
            <div class="text-end my-3 p-1">
                <a class="btn btn-success" asp-asp-controller="Application" asp-action="Create"> Yeni İlan Oluştur</a>

            </div>


            <table class="mt-4 table table-sm table-hover table-striped">
                <thead>
                    <tr>

                        <td> İlan Başlığı</td>
                        <td> İlan Tarihi </td>
                        <td> İlan durumu </td>
                        <td> İşlemler</td>


                    </tr>
                </thead>

                <tbody>
                    @foreach (var advertisement in Model)
                    {
                        <tr>
                            <td> @advertisement.Title</td>
                            <td> @advertisement.CreatedDate.ToString("dddd, dd MMMM yyyy")</td>
                            <td> @(advertisement.status ? "Aktif" : "Pasif")</td>

                            <td>

                                <a class="btn btn-success" asp-action="Update" asp-asp-controller="Application" asp-route-id="@advertisement.Id"> Güncelle</a>
                                <a class="btn btn-danger" asp-action="Remove" asp-asp-controller="Application" asp-route-id="@advertisement.Id"> Sil</a>
                            </td>

                        </tr>
                    }

                </tbody>
            </table>
        }
        else
        {

            <div class="mt-3 text-center lead">


                <a class="btn btn-success" asp-asp-controller="Application" asp-action="Create"> Yeni İlan Oluştur</a>

                <p>Herhangi Bir İlan  bulunamamıştır.  </p>

            </div>
        }
    }

</div>

AdvertisementProject/AdvertisementApp/AdvertisementApp.Presentation/Views/Application/Update.cshtml
@model AdvertisementUpdateDto
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <form asp-action="Update" asp-controller="Application" method="post">
        <input  type="hidden" asp-for="@Model.Id"/>
        <div class="mb-3">
            <label> İlanın Başlığı </label>
            <input type="text" class="form-control" asp-for="@Model.Title" />
        </div>
        <div class="mb-3">
            <label class="form-check-label"> Aktif </label>
            <input type="checkbox" class="form-check-input" asp-for="@Model.status" />
        </div>

        <div class="mb-3">
            <lable> İçerik</lable>
            <textarea asp-for="@Model.Description" class="form-control"> </textarea>

        </div>
        <div class="mb-3">

            <button class="btn btn-primary"> Kaydet</button>
        </div>
    </form>

</div>


@section script{

    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/vendor/jquery-3.3.1.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.26.0/trumbowyg.min.js" integrity="sha512-ZfWLe+ZoWpbVvORQllwYHfi9jNHUMvXR4QhjL1I6IRPXkab2Rquag6R0Sc1SWUYTj20yPEVqmvCVkxLsDC3CRQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script>
        $(document).ready(function () {
            $("#Description").trumbowyg();

        });
    </script>
}

@section css{

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.26.0/ui/trumbowyg.min.css" integrity="sha512-Zi7Hb6P4D2nWzFhzFeyk4hzWxBu/dttyPIw/ZqvtIkxpe/oCAYXs7+tjVhIDASEJiU3lwSkAZ9szA3ss3W0Vug==" crossorigin="anonymous" referrerpolicy="no-referrer" />
}